name: Playwright Tests in Docker
on:
    push:
        branches: [develop]
    pull_request:
        branches: [develop]

jobs:
    test:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        container:
            # Використовуємо офіційний образ Playwright (або ваш зібраний)
            image: mcr.microsoft.com/playwright:v1.54.1-jammy
            options: --shm-size=2gb # Важливо для стабільності браузерів!

        steps:
            - uses: actions/checkout@v4

            # Встановлюємо залежності та запускаємо тести всередині контейнера
            - name: Install dependencies and run tests
              run: |
                  npm ci --force
                  cd pw-practice-app && npm ci --force && cd ..
                  npx playwright test --workers=1 --timeout=60000

            # Артефакти (звіти)
            - uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 30
